language: python
sudo: false
dist: xenial
python:
    - 2.7
    - 3.6
    - 3.7
install:
    - pip install -U setuptools pip
    - pip install zc.buildout
    - buildout annotate
    - buildout
script:
    - bin/test -v1
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
